### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by tigercosmos** [xlpiao/.xlpiao#1]
Hi @xlpiao,

Sorry for disturbing you. I cannot send an email to hlpark@skku.edu, so leave a message here.

I am Liu, An-Chi, a CS master student in NCTU, Taiwan. I have read your papers. These papers are really inspiring, but they are short and missed most of the details. I am wondering that may I access your Ph.D. or master thesis?

**Comment by xlpiao** [comment]
@tigercosmos Hi, can I know which paper did you read ?
Here's the list: https://scholar.google.co.kr/citations?user=fqPaaBAAAAAJ&hl=en 
Tell me the paper you read so that I can help as much as possible.

**Comment by tigercosmos** [comment]
@xlpiao I have read "JAWS: a JavaScript framework for adaptive CPU-GPU work sharing" and "Efficient CPU-GPU work sharing for data-parallel JavaScript workloads." These papers are two-page long, so I am looking for something with more content, and I thought your degree thesis might be good reading.

I thought "Automatic Runtime Selection of Best Hardware for Data-Parallel JavaScript Kernels via Lifelong Profiling" probably is your thesis and the previous two are based on it? However, this paper cannot be accessed through Google Scholar.

**Comment by xlpiao** [comment]
@tigercosmos , can you email me so that I can send you master thesis. My email address is  xianglan0502 (at) gmail (dot) com

**Comment by xlpiao** [comment]
@tigercosmos You can check my email address at https://www.linkedin.com/in/xlpiao/detail/contact-info/
Can you email me so that I can send you the master thesis ?

**Comment by tigercosmos** [comment]
@xlpiao sent. great thanks.
